version: "3.7"

services:
  dev-arm:
    build:
      context: .
      dockerfile: Dockerfile.arm
    ports:
      - "1234:1234"
      - "2222:2222"
    networks:
      - os_share_network
    volumes:
      - ../:/root/SynestiaOS
    privileged: true
  dev-riscv:
    build:
      context: .
      dockerfile: Dockerfile.riscv
    ports:
      - "1234:1234"
      - "2222:2222"
    networks:
      - os_share_network
    volumes:
      - ../:/root/SynestiaOS
    privileged: true
  dev-prebuilt:
    image: synestiaos/synestiaos:devel
    ports:
      - "1234:1234"
      - "2222:2222"
    networks:
      - os_share_network
    volumes:
      - ../:/root/SynestiaOS
    privileged: true



networks:
  os_share_network:
